# Generated by Django 6.0.3 on 2026-04-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500, verbose_name='Текст вопроса')),
                ('option1', models.CharField(max_length=200, verbose_name='Вариант 1')),
                ('option2', models.CharField(max_length=200, verbose_name='Вариант 2')),
                ('option3', models.CharField(max_length=200, verbose_name='Вариант 3')),
                ('option4', models.CharField(max_length=200, verbose_name='Вариант 4')),
                ('correct_option', models.PositiveSmallIntegerField(verbose_name='Правильный вариант (1-4)')),
                ('explanation', models.TextField(verbose_name='Пояснение')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
